ワールド一覧の描画ルールを変更
Server-Starter-for-Minecraft/ServerStarter2 pull request #159
Opened 2024-03-09 10:57 UTC by CivilTT

# ワールド一覧の描画ルールを変更

#155 で言及しているワールド一覧に表示するワールドがなくなった場合の処理を追加

## 変更箇所

- [ ] ソフト起動時に読み込むワールド一覧を描画するワールド一覧に変更することで，一覧の表示件数が0の時に新規ワールドを追加する処理が正しく動作するように修正
  - [ ] 上記の修正をワールド削除時の件数確認処理にも適用
- [ ] ワールド検索の際に表示するワールドがない場合の画面を追加
  - [ ] 検索時にヒットしたワールドが検索前に表示していたワールドではない場合に，ヒットしたワールドのうち一番上に表示されているワールドを表示する仕様に変更
  - [ ] 表示中のワールドがヒットしたワールドの中に入っているときは表示を変更しない
- [ ] ワールドフォルダの非表示ボタンの仕様を変更
  - [ ] 当該フォルダが選択されているときには，ワールドフォルダを非表示できない仕様に変更
  （以前までは非表示にできてしまったため，当該ワールドフォルダに属するワールドは非表示になっても当該ワールドだけは表示され続けてしまい，直感的ではない挙動だった）
  - [ ] デフォルトのワールドフォルダ（ワールドフォルダリストの一番上に表示されているフォルダ）は非表示にできない仕様に変更
  （ソフト起動時に自動追加するワールドはデフォルトのワールドフォルダになるため，これが非表示になると追加されたはずのワールドが表示されなくなる）

## 承認者への申し送り事項

エラーワールドのみのワールドをワールドフォルダに追加し，デフォルトの保存場所からすべてのワールドを削除した状態で起動し，新しいワールドが自動で１つ追加されるようになっていることを確認してください

また，このほかにも上記の変更点が正しく反映され，ユーザーの操作として直感的であることを確認してください

2024-03-24 09:46 UTC, nozz-mat reviewed
TestDataCollectionを利用して検証
- 検索関係
  - ワールド検索で表示可能なワールドがない際に専用の画面が表示されることを確認
  - 翻訳の反映を確認
- ワールドの非表示ボタン
  - デフォルトの保存先が非表示にできないことを確認
  - 選択中のワールドが含まれている保存先を非表示にできないことを確認
-エラーワールドのみのワールドをワールドフォルダに追加し，デフォルトの保存場所からすべてのワールドを削除した状態で起動し，新しいワールドが自動で１つ追加されるようになっていることを確認

2024-03-24 09:50 UTC, nozz-mat requested changes
- ワールド検索画面で選択中のワールド以外がヒットする際、選択中のワールドが自動的に切り替わる挙動は直感的ではないように感じました
  - 適当な文字列を検索窓に打ち込んだ際に意図しないワールドが選択されて困りそうです
- 検索結果としてヒットしたワールドを表示するだけにし、選択中のワールドは勝手に変更されない方が直感的だと思います

2024-03-26 16:13 UTC, CivilTT commented
@nozz-mat 
自動選択の機構を削除したため，動作の確認をお願いします．
一方で，下記のような理由により，特別変な挙動という考えがなければ自動選択は導入した方が良いと感じます．

- 検索している時点でユーザーはマウスクリックと同様にワールドを意識的に「選択している」と考えられる
- UI的にワールド一覧と右側の編集画面は対応している構成にしているため，検索によって選択中のワールドが対象外になった際，ワールド一覧の中で選択中のワールドがない状態が不自然なうえ，右側の編集画面に表示されているワールドがワールド一覧にない状況も不自然．ワールド一覧で選択中のワールドと編集画面に表示しているワールドは常に対応しているべき．
    - ユーザーの目線移動を考えたときに，検索欄で検索を行い，その下に表示されたワールドを確認し，右側の編集欄に目を移していく．検索結果が複数のワールドの時にはどのワールドを表示するか選択する行動が発生するが，１つしか検索結果がなかった場合，そのワールドを編集できるものと勘違いさせてしまう可能性があるため，避けたい．
- 「検索前に表示していたワールドへ関心がある」という状況（直近に起動したわけではない古いワールドを意識的に選択した後にワールドの検索を行う，というような状況）はあまり多くないと考えられる．
- （最新版のOutlookでは検索欄への入力直後に検索結果の中で一番直近のメールを自動選択する仕様になっている）

次回打ち合わせ時にそれぞれの挙動を見ながら最終的な仕様を決めましょう

2024-03-30 13:30 UTC, nozz-mat commented
自動選択の機構が削除されていることを確認しました

- 検索欄に'N','n','an','a'を入力した際に検索結果に全てのワールドが表示された状態になります(該当する文字列が含まれていないワールドの表示が消えません)
'N'のみを入力した例を示します(hogeは非表示になって欲しいのに残っている)
<img width="392" alt="スクリーンショット 2024-03-30 22 20 49" src="https://github.com/Server-Starter-for-Minecraft/ServerStarter2/assets/104409861/d9ca42d1-89b4-4619-8b3d-454b75c88759">

- 自動選択の機構を削除するなら'表示可能なワールドがありません'の画面も必要なくなるので合わせて削除していいと思います
詳細は打ち合わせ時に決めましょう

2024-04-27 16:52 UTC, CivilTT commented
ワールド検索のロジックを添付の状態遷移図に基づいて修正しています
![image](https://github.com/Server-Starter-for-Minecraft/ServerStarter2/assets/89191801/819c154e-0837-4d3e-abe8-92a88afa7108)

2024-05-04 15:42 UTC, nozz-mat approved these changes
前回の打ち合わせで想定通りの挙動をすることを確認したことを持って承認とします。

2024-05-04 15:42 UTC, merged