runtimeを作成
Server-Starter-for-Minecraft/ServerStarter2 pull request #209
Opened 2024-07-27 18:16 UTC by txkodo

# javaのインストールと削除のための機能を実装

- minecraftランタイムの場合は対応するランタイムをURL経由で取得
- universalの場合はバージョンがあっている他のランタイムを代わりにインストールする
  - univerasl 21 の場合  java-runtime-delta が入るといった具合
  - 何をインストールすべきかの対応情報はOuterResourceで管理予定

2024-07-30 16:21 UTC, CivilTT approved these changes
以下の内容を確認し，問題ないことを確認しました

- 全ての既存のテストを実行
- テストケースにredhatを追加しても問題なく動作することを確認
- キャッシュのアンインストールをコメントアウトした際にキャッシュを使った読み込みが実行され，処理速度が改善することを確認

一方で下記の問題がありましたが，今回は重要ではないためスルーとします
- インターネット切断時にManifestのダウンロードを無限に待機するためシステム全体がフリーズする可能性がある

2024-08-14 15:25 UTC, CivilTT requested changes
Runtimeのテストで非常に長い時間待機が発生してしまう問題が残存しているため，これの修正をお願いします

2024-09-01 07:26 UTC, txkodo commented
skipとしてマークしました。

2024-09-04 15:24 UTC, CivilTT commented
Vitestによればテストを通らない項目が残っているようですが，これらの原因と対策を教えてください

2024-09-08 13:42 UTC, CivilTT approved these changes
ローカルにて，テストが正常に作動することを確認
カバレッジについても確認しましたが，カバー外とされている箇所であってもテストで言及がある，または，重大な機能ではないことを確認したため，承認とします

2024-09-08 13:42 UTC, merged